volumes:
  dbdata6:

services:
  mongo:
    image: mongo
    volumes: 
    - dbdata6:/data/db
    - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    environment:
      MONGO_INITDB_DATABASE: $MONGODB_DATABASE
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
    command: mongod --help
    ports:
      - $MONGODB_PORT:27017
